<a href="https://colab.research.google.com/github/L-y-t-h-r-u-m/Demo-Test/blob/main/00_pytorch_fundamentals_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124



## Introduction to tensors

### Creating tensors

Pytorch tensors are created using `torch.Tensor()`


In [51]:



#scalar
scalar = torch.tensor(7)
scalar



tensor(7)

In [52]:
# to get tensor dimensions
scalar.ndim

0

In [53]:
# get tensor back as python int
scalar.item()

7

In [54]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [55]:
vector.ndim

1

In [56]:
vector.shape

torch.Size([2])

In [57]:
matrix = torch.tensor([[3,4],
                       [5,0]])
matrix

tensor([[3, 4],
        [5, 0]])

In [58]:
matrix.ndim

2

In [59]:
matrix[1]

tensor([5, 0])

In [60]:
matrix.shape

torch.Size([2, 2])

### Random Tensors

In [61]:
# Create a random tensor of size (3,4)
randomTensor = torch.rand(1,3,4)
randomTensor

tensor([[[0.9358, 0.0131, 0.1393, 0.9943],
         [0.4961, 0.4863, 0.5989, 0.0391],
         [0.3959, 0.4994, 0.9333, 0.4100]]])

In [62]:
# Create a random tensor with similar shape to an image tensor
randomImageSizeTensor = torch.rand(size=(3,224,224)) # height, width, color channel
randomImageSizeTensor.shape, randomImageSizeTensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and Ones


In [63]:
# creating a tensor of all zeroes

zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [64]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

###Creating a range of tensors and tensors-like

In [65]:
# torch.range()
one_to_ten = torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
torch.arange(start=0, end=1000, step = 23)

tensor([  0,  23,  46,  69,  92, 115, 138, 161, 184, 207, 230, 253, 276, 299,
        322, 345, 368, 391, 414, 437, 460, 483, 506, 529, 552, 575, 598, 621,
        644, 667, 690, 713, 736, 759, 782, 805, 828, 851, 874, 897, 920, 943,
        966, 989])

In [67]:
# creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on right device


In [68]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

### Getting information from tensors

In [69]:
#shape, dtype, device
someTensor = torch.rand(3,4)

print(someTensor)
print(f"Shape of tensor: {someTensor.shape}")
print(f"Datatype of tensor: {someTensor.dtype}")
print(f"Device tensor is stored on: {someTensor.device}")

tensor([[0.5782, 0.6954, 0.4504, 0.9445],
        [0.9575, 0.5163, 0.7427, 0.3238],
        [0.3979, 0.0213, 0.3528, 0.2393]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensor fundamentals

In [70]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [71]:
#multiplication
tensor*10

tensor([10, 20, 30])

In [72]:
tensor

tensor([1, 2, 3])

In [73]:
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [74]:
tensor = tensor - 10
tensor

tensor([1, 2, 3])

In [75]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [76]:
tensor

tensor([1, 2, 3])

In [77]:
#element wise multiplication
print(tensor, "*", tensor)
print("Equals: ", tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [78]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [79]:
tensor @ tensor

tensor(14)

In [80]:
%%time
value = 0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
value

CPU times: user 440 µs, sys: 0 ns, total: 440 µs
Wall time: 452 µs


tensor(14)

In [81]:
%%time
torch.mm(tensor, tensor)

RuntimeError: self must be a matrix

### Finding min, max, mean (Tensor aggreagation)

In [82]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
print(f"Minimum: {x.min()}");
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


### Finding positional min max

In [84]:
x.argmin()

tensor(0)

In [85]:
x.argmax()

tensor(9)